apiVersion:  v1  #acts a manuall to your system
kind: Pod
metadata:  #like a tag
        name: mypod
        namespace: tododevenv
        labels:
         app: mypod      
spec:
 containers:
    - name: mypod-cont
      image: akashlandge/todo
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
---
apiVersion: v1 
kind: Service
metadata:
        name: lb  #cluster
        namespace: tododevenv 
spec:
    selector:
          app: mypod  
    type: LoadBalancer 
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: todo
---
apiVersion: v1
kind: Namespace
metadata:
  name: mypod
  labels:
        app: mypod
        