apiVersion:  v1  
kind: Pod
metadata:  
        name: project
        labels:
         app: project      
spec:
 containers:
    - name: project-cont1
      image: apiVersion:  v1  
kind: Pod
metadata:  #like a tag
        name: project
        labels:
         app: project      
spec:
 containers:
    - name: project-cont1
      image: akashlandge/project
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
---
apiVersion: v1 
kind: Service
metadata:
        name: lb   
spec:
    selector:
          app: project  
    type: LoadBalancer 
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: todo
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
---
apiVersion: v1 
kind: Service
metadata:
        name: lb   
spec:
    selector:
          app: project  
    type: LoadBalancer 
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: project