apiVersion:  autoscaling/v2
kind:  HorizontalPodAutoscaler
metadata:  
    name: hpa1 
    labels:
        app: hpa1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploymentapp
  minReplicas: 1  #if below 50% scale down to 1
  maxReplicas: 2  #if above 50% scale up to 2
  metrics:  #data metrics parameter
  - type: Resource
    resource:
      name: cpu  #the type of resource that to be monitored
      target:
        type: Utilization   #cpu utilization condition
        averageUtilization: 50  #cpu utilization threshold in %
        