apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
       name: studentappreplica2
       labels:
            app: studentappreplica2
spec: 
    replicas: 4  #how many replica's you want to create on the basis of template
    template:
      metadata:  #like a tag
         labels: 
            app: studentappreplica2
      spec:
        containers:
            - name: mypod-cont1
              image: nginx:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: http
                  containerPort: 80
                  protocol: TCP
    selector:
          matchLabels:
                app: studentappreplica2
          # matchExpressions: 
          #   - {key: app, operator: In, values: [webappreplica, mobappreplica]}