apiVersion: apps/v1
kind: StatefulSet 
metadata: 
       name: Stateful
       labels:
            app: Stateful
spec: 
    replicas: 5  #how many replica's you want to create on the basis of template
    template:
      metadata:  #like a tag
         name: Stateful
         labels: 
            app: Stateful
      spec:
        containers:
            - name: mypod-cantainer
              image: mysql:latest
              resources: 
                  requests:
                    cpu: "100m"
                    memory: "100Mi"        
              ports:  
                - name: dbport
                  containerPort: 3306
                  protocol: TCP
              env:
                 - name: MYSQL_ROOT_PASSWORD
                   value: "1234"
    selector:
        matchLabels:
          app: Stateful